services:
  # ==========================================
  # LAPTOP 2: Processing Layer (Nadhifa)
  # ==========================================
  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master-laptop2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./processing:/app

  spark-worker:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-worker-laptop2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081" # Spark Worker Web UI
    depends_on:
      - spark-master
    volumes:
      - ./processing:/app

  # Jupyter PySpark untuk development kode
  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter-laptop2
    ports:
      - "8888:8888" # Jupyter Notebook UI
      - "4040:4040" # Spark Application UI
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    volumes:
      - ./processing:/home/jovyan/work
