services:
  
  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter-laptop2
    ports:
      - "8888:8888" # Jupyter Notebook UI
      - "4040:4040" # Spark Application UI
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    volumes:
      - ./processing:/home/jovyan/work
