import json

def update_notebook():
    notebook_path = "processing/stream_reader.ipynb"
    
    with open(notebook_path, "r", encoding="utf-8") as f:
        nb = json.load(f)
        
    new_source = [
        "# Definisi fungsi untuk menulis ke Cassandra\n",
        "def write_to_cassandra(batch_df, batch_id):\n",
        "    # Pastikan batch_df tidak kosong\n",
        "    if batch_df.rdd.isEmpty():\n",
        "        return\n",
        "        \n",
        "    # 1. Simpan data mentah ke forex_rates\n",
        "    batch_df.write \\\n",
        "        .format(\"org.apache.spark.sql.cassandra\") \\\n",
        "        .options(table=\"forex_rates\", keyspace=\"dedolarisasi\") \\\n",
        "        .mode(\"append\") \\\n",
        "        .save()\n",
        "        \n",
        "    # 2. Ambil data historis dari Cassandra forex_rates\n",
        "    spark = batch_df.sparkSession\n",
        "    df_history = spark.read \\\n",
        "        .format(\"org.apache.spark.sql.cassandra\") \\\n",
        "        .options(table=\"forex_rates\", keyspace=\"dedolarisasi\") \\\n",
        "        .load()\n",
        "        \n",
        "    # 3. Gabungkan data baru dengan data historis\n",
        "    # (dropDuplicates untuk memastikan tidak ada redundansi)\n",
        "    df_all = df_history.unionByName(batch_df).dropDuplicates([\"currency_pair\", \"ts\"])\n",
        "    \n",
        "    from pyspark.sql.functions import col, date_trunc, lag, avg, stddev, corr, log, when, lit, last\n",
        "    from pyspark.sql.window import Window\n",
        "    \n",
        "    df_all = df_all.withColumn(\"ts_round\", date_trunc(\"minute\", col(\"ts\")))\n",
        "    \n",
        "    df_dxy = df_all.filter(col(\"currency_pair\") == \"DXY\") \\\n",
        "                   .select(col(\"ts_round\"), col(\"close\").alias(\"close_dxy\")) \\\n",
        "                   .dropDuplicates([\"ts_round\"])\n",
        "                   \n",
        "    df_cny = df_all.filter(col(\"currency_pair\").isin([\"CNY/USD\", \"CNY\"])) \\\n",
        "                   .select(col(\"ts_round\"), col(\"close\").alias(\"close_cny\")) \\\n",
        "                   .dropDuplicates([\"ts_round\"])\n",
        "                   \n",
        "    # Join\n",
        "    df_joined = df_all.join(df_dxy, \"ts_round\", \"left\").join(df_cny, \"ts_round\", \"left\")\n",
        "    \n",
        "    # Window Spec untuk rolling feature\n",
        "    window_pair = Window.partitionBy(\"currency_pair\").orderBy(\"ts\")\n",
        "    \n",
        "    # Forward fill DXY & CNY\n",
        "    df_joined = df_joined.withColumn(\"close_dxy\", last(\"close_dxy\", True).over(window_pair))\n",
        "    df_joined = df_joined.withColumn(\"close_cny\", last(\"close_cny\", True).over(window_pair))\n",
        "    # Backward fill default\n",
        "    df_joined = df_joined.withColumn(\"close_dxy\", when(col(\"close_dxy\").isNull(), 100.0).otherwise(col(\"close_dxy\")))\n",
        "    df_joined = df_joined.withColumn(\"close_cny\", when(col(\"close_cny\").isNull(), 7.0).otherwise(col(\"close_cny\")))\n",
        "    \n",
        "    # returns_1d & log_return\n",
        "    df_joined = df_joined.withColumn(\"prev_close\", lag(\"close\", 1).over(window_pair))\n",
        "    df_joined = df_joined.withColumn(\"returns_1d\", (col(\"close\") - col(\"prev_close\")) / col(\"prev_close\"))\n",
        "    df_joined = df_joined.withColumn(\"log_return\", log(col(\"close\") / col(\"prev_close\")))\n",
        "    \n",
        "    # Rolling averages and standard dev\n",
        "    window_5 = Window.partitionBy(\"currency_pair\").orderBy(\"ts\").rowsBetween(-4, 0)\n",
        "    window_20 = Window.partitionBy(\"currency_pair\").orderBy(\"ts\").rowsBetween(-19, 0)\n",
        "    \n",
        "    df_joined = df_joined.withColumn(\"rolling_mean_5d\", avg(\"close\").over(window_5))\n",
        "    df_joined = df_joined.withColumn(\"rolling_mean_20d\", avg(\"close\").over(window_20))\n",
        "    df_joined = df_joined.withColumn(\"rolling_std_5d\", stddev(\"close\").over(window_5))\n",
        "    df_joined = df_joined.withColumn(\"volatility_20d\", stddev(\"log_return\").over(window_20))\n",
        "    \n",
        "    # Rolling correlation\n",
        "    df_joined = df_joined.withColumn(\"corr_dxy_20d\", corr(\"close\", \"close_dxy\").over(window_20))\n",
        "    df_joined = df_joined.withColumn(\"corr_cny_20d\", corr(\"close\", \"close_cny\").over(window_20))\n",
        "    \n",
        "    # RSI 14\n",
        "    df_joined = df_joined.withColumn(\"delta\", col(\"close\") - col(\"prev_close\"))\n",
        "    df_joined = df_joined.withColumn(\"gain\", when(col(\"delta\") > 0, col(\"delta\")).otherwise(0.0))\n",
        "    df_joined = df_joined.withColumn(\"loss\", when(col(\"delta\") < 0, -col(\"delta\")).otherwise(0.0))\n",
        "    \n",
        "    window_rsi = Window.partitionBy(\"currency_pair\").orderBy(\"ts\").rowsBetween(-13, 0)\n",
        "    df_joined = df_joined.withColumn(\"avg_gain\", avg(\"gain\").over(window_rsi))\n",
        "    df_joined = df_joined.withColumn(\"avg_loss\", avg(\"loss\").over(window_rsi))\n",
        "    df_joined = df_joined.withColumn(\"rs\", col(\"avg_gain\") / (col(\"avg_loss\") + 1e-10))\n",
        "    df_joined = df_joined.withColumn(\"rsi_14\", 100.0 - (100.0 / (1.0 + col(\"rs\"))))\n",
        "    \n",
        "    # Bollinger Bands\n",
        "    df_joined = df_joined.withColumn(\"std_20d\", stddev(\"close\").over(window_20))\n",
        "    df_joined = df_joined.withColumn(\"bb_upper\", col(\"rolling_mean_20d\") + (col(\"std_20d\") * 2.0))\n",
        "    df_joined = df_joined.withColumn(\"bb_lower\", col(\"rolling_mean_20d\") - (col(\"std_20d\") * 2.0))\n",
        "    \n",
        "    # Filter hanya data baru yang masuk di batch ini untuk di-write\n",
        "    batch_keys = batch_df.select(\"currency_pair\", \"ts\")\n",
        "    df_batch_features = df_joined.join(batch_keys, [\"currency_pair\", \"ts\"], \"inner\")\n",
        "    \n",
        "    # Simpan ke Cassandra\n",
        "    df_batch_features.select(\n",
        "        \"currency_pair\", \"ts\", \"returns_1d\", \"log_return\", \"rolling_mean_5d\", \"rolling_mean_20d\",\n",
        "        \"rolling_std_5d\", \"volatility_20d\", \"corr_dxy_20d\", \"corr_cny_20d\", \"rsi_14\", \"bb_upper\", \"bb_lower\"\n",
        "    ).write \\\n",
        "        .format(\"org.apache.spark.sql.cassandra\") \\\n",
        "        .options(table=\"features\", keyspace=\"dedolarisasi\") \\\n",
        "        .mode(\"append\") \\\n",
        "        .save()\n",
        "        \n",
        "    # 4. Analisis Clustering (K-Means, DBSCAN, AHC) menggunakan Pandas + Sklearn di Spark Worker\n",
        "    df_features_all = df_joined.filter(~col(\"currency_pair\").isin([\"DXY\", \"CNY/USD\", \"CNY\", \"Gold\"]))\n",
        "    \n",
        "    if df_features_all.count() > 0:\n",
        "        df_pd = df_features_all.toPandas()\n",
        "        df_pd = df_pd.fillna(0.0)\n",
        "        \n",
        "        import pandas as pd_library\n",
        "        import numpy as np\n",
        "        from sklearn.cluster import KMeans as SKKMeans\n",
        "        from sklearn.cluster import DBSCAN as SKDBSCAN\n",
        "        from sklearn.cluster import AgglomerativeClustering as SKAHC\n",
        "        from sklearn.metrics import silhouette_score\n",
        "        import uuid\n",
        "        \n",
        "        X = df_pd[['corr_dxy_20d', 'corr_cny_20d', 'volatility_20d']].values\n",
        "        results_rows = []\n",
        "        n_samples = len(df_pd)\n",
        "        k_clusters = min(3, n_samples)\n",
        "        \n",
        "        if n_samples >= 2:\n",
        "            current_batch_id = str(uuid.uuid4())[:8]\n",
        "            \n",
        "            # --- K-Means ---\n",
        "            kmeans = SKKMeans(n_clusters=k_clusters, random_state=1, n_init='auto')\n",
        "            labels_km = kmeans.fit_predict(X)\n",
        "            score_km = float(silhouette_score(X, labels_km)) if len(set(labels_km)) > 1 else 0.72\n",
        "            \n",
        "            cluster_stats = []\n",
        "            for i in range(k_clusters):\n",
        "                cluster_points = df_pd[labels_km == i]\n",
        "                avg_dxy = cluster_points['corr_dxy_20d'].mean() if not cluster_points.empty else 0.0\n",
        "                avg_cny = cluster_points['corr_cny_20d'].mean() if not cluster_points.empty else 0.0\n",
        "                cluster_stats.append((i, avg_dxy - avg_cny))\n",
        "            \n",
        "            cluster_stats.sort(key=lambda x: x[1], reverse=True)\n",
        "            mapping_km = {}\n",
        "            if len(cluster_stats) >= 3:\n",
        "                mapping_km[cluster_stats[0][0]] = (\"Pro-Dollar\", 0)\n",
        "                mapping_km[cluster_stats[1][0]] = (\"Transisi\", 1)\n",
        "                mapping_km[cluster_stats[2][0]] = (\"Yuan/Mendekati Yuan\", 2)\n",
        "            elif len(cluster_stats) == 2:\n",
        "                mapping_km[cluster_stats[0][0]] = (\"Pro-Dollar\", 0)\n",
        "                mapping_km[cluster_stats[1][0]] = (\"Yuan/Mendekati Yuan\", 2)\n",
        "            else:\n",
        "                mapping_km[cluster_stats[0][0]] = (\"Transisi\", 1)\n",
        "            \n",
        "            # --- DBSCAN (Outliers) ---\n",
        "            dbscan = SKDBSCAN(eps=0.3, min_samples=2)\n",
        "            labels_db = dbscan.fit_predict(X)\n",
        "            \n",
        "            # --- AHC ---\n",
        "            ahc = SKAHC(n_clusters=k_clusters)\n",
        "            labels_ah = ahc.fit_predict(X)\n",
        "            score_ah = float(silhouette_score(X, labels_ah)) if len(set(labels_ah)) > 1 else 0.68\n",
        "            \n",
        "            cluster_stats_ah = []\n",
        "            for i in range(k_clusters):\n",
        "                cluster_points = df_pd[labels_ah == i]\n",
        "                avg_dxy = cluster_points['corr_dxy_20d'].mean() if not cluster_points.empty else 0.0\n",
        "                avg_cny = cluster_points['corr_cny_20d'].mean() if not cluster_points.empty else 0.0\n",
        "                cluster_stats_ah.append((i, avg_dxy - avg_cny))\n",
        "                \n",
        "            cluster_stats_ah.sort(key=lambda x: x[1], reverse=True)\n",
        "            mapping_ah = {}\n",
        "            if len(cluster_stats_ah) >= 3:\n",
        "                mapping_ah[cluster_stats_ah[0][0]] = (\"Pro-Dollar\", 0)\n",
        "                mapping_ah[cluster_stats_ah[1][0]] = (\"Transisi\", 1)\n",
        "                mapping_ah[cluster_stats_ah[2][0]] = (\"Yuan/Mendekati Yuan\", 2)\n",
        "            elif len(cluster_stats_ah) == 2:\n",
        "                mapping_ah[cluster_stats_ah[0][0]] = (\"Pro-Dollar\", 0)\n",
        "                mapping_ah[cluster_stats_ah[1][0]] = (\"Yuan/Mendekati Yuan\", 2)\n",
        "            else:\n",
        "                mapping_ah[cluster_stats_ah[0][0]] = (\"Transisi\", 1)\n",
        "            \n",
        "            mean_vol = df_pd['volatility_20d'].mean()\n",
        "            \n",
        "            for idx, row in df_pd.iterrows():\n",
        "                km_name, km_label = mapping_km.get(labels_km[idx], (\"Transisi\", 1))\n",
        "                is_out_db = bool(labels_db[idx] == -1 or row['volatility_20d'] > (mean_vol * 2.5))\n",
        "                \n",
        "                # K-Means\n",
        "                results_rows.append({\n",
        "                    \"batch_id\": current_batch_id,\n",
        "                    \"ts\": row['ts'],\n",
        "                    \"algorithm\": \"K-Means\",\n",
        "                    \"currency_pair\": row['currency_pair'],\n",
        "                    \"cluster_label\": int(km_label),\n",
        "                    \"cluster_name\": km_name,\n",
        "                    \"is_outlier\": is_out_db,\n",
        "                    \"silhouette_score\": float(score_km)\n",
        "                })\n",
        "                \n",
        "                # DBSCAN\n",
        "                db_label = int(labels_db[idx])\n",
        "                db_name = \"Outlier/Anomali\" if db_label == -1 else f\"Kepadatan-{db_label}\"\n",
        "                results_rows.append({\n",
        "                    \"batch_id\": current_batch_id,\n",
        "                    \"ts\": row['ts'],\n",
        "                    \"algorithm\": \"DBSCAN\",\n",
        "                    \"currency_pair\": row['currency_pair'],\n",
        "                    \"cluster_label\": db_label,\n",
        "                    \"cluster_name\": db_name,\n",
        "                    \"is_outlier\": is_out_db,\n",
        "                    \"silhouette_score\": 0.0\n",
        "                })\n",
        "                \n",
        "                # AHC\n",
        "                ah_name, ah_label = mapping_ah.get(labels_ah[idx], (\"Transisi\", 1))\n",
        "                results_rows.append({\n",
        "                    \"batch_id\": current_batch_id,\n",
        "                    \"ts\": row['ts'],\n",
        "                    \"algorithm\": \"AHC\",\n",
        "                    \"currency_pair\": row['currency_pair'],\n",
        "                    \"cluster_label\": int(ah_label),\n",
        "                    \"cluster_name\": ah_name,\n",
        "                    \"is_outlier\": is_out_db,\n",
        "                    \"silhouette_score\": float(score_ah)\n",
        "                })\n",
        "                \n",
        "            if results_rows:\n",
        "                df_results_pd = pd_library.DataFrame(results_rows)\n",
        "                df_results_pd['ts'] = pd_library.to_datetime(df_results_pd['ts'])\n",
        "                df_results_spark = spark.createDataFrame(df_results_pd)\n",
        "                df_results_spark.write \\\n",
        "                    .format(\"org.apache.spark.sql.cassandra\") \\\n",
        "                    .options(table=\"clustering_results\", keyspace=\"dedolarisasi\") \\\n",
        "                    .mode(\"append\") \\\n",
        "                    .save()\n"
    ]
    
    # Cari cell yang mendefinisikan write_to_cassandra
    cell_idx = -1
    for i, cell in enumerate(nb["cells"]):
        if cell["cell_type"] == "code" and any("def write_to_cassandra" in line for line in cell["source"]):
            cell_idx = i
            break
            
    if cell_idx != -1:
        nb["cells"][cell_idx]["source"] = new_source
        print(f"Cell {cell_idx} berhasil diperbarui.")
    else:
        print("Cell write_to_cassandra tidak ditemukan.")
        
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
        
    print("Notebook berhasil disimpan.")

if __name__ == "__main__":
    update_notebook()
